# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

"""Mock MSRC service.

This service exists only to demonstrate the workflow. It makes no production
claims: enrollment is unauthenticated, submissions are unauthenticated, and
the certificate authority material is demo material generated by the launcher.
"""

from __future__ import annotations

import base64
from pathlib import Path
from typing import Any, Final

from fastapi import APIRouter, FastAPI, File, Form, Request, Response, UploadFile

from .. import operations
from ..config import Settings
from ..errors import ConfigurationError, NotFoundError
from ..http_support import (
    artifact_response,
    attach_services,
    get_services,
    install_error_handlers,
    now_text,
)
from ..models import (
    EnrollmentIssuance,
    HealthResponse,
    PresentationResponse,
    SelectionRequest,
    StoredSubmission,
    StoredSubmissionList,
)
from ..services import Services, build_services
from ..storage import new_record_id, validate_record_id
from ..uploads import (
    BUNDLE_UPLOAD,
    PUBLIC_KEY_UPLOAD,
    check_text_field,
    read_upload,
)

router = APIRouter(tags=["mock-msrc"])

ENROLLMENTS: Final = "msrc_enrollments"
SUBMISSIONS: Final = "msrc_submissions"
LEAF_FILE: Final = "leaf.pem"
PUBLIC_KEY_FILE: Final = "public.pem"
META_FILE: Final = "meta.json"
BUNDLE_FILE: Final = "bundle.cbor"
PRESENTED_PREFIX: Final = "presented"
MAX_SHORT_CHARS: Final = 200

DEMO_NOTICE: Final = (
    "Mock MSRC service for demonstration only. It performs no authentication, "
    "no triage and no production issuance."
)


def _root_material(settings: Settings) -> tuple[Path, Path]:
    if settings.msrc_root_key is None or settings.msrc_root_cert is None:
        raise ConfigurationError(
            "The mock MSRC certificate authority is not configured.",
            detail="Set SDC_MSRC_ROOT_KEY and SDC_MSRC_ROOT_CERT.",
        )
    if not settings.msrc_root_key.is_file() or not settings.msrc_root_cert.is_file():
        raise ConfigurationError(
            "The mock MSRC certificate authority material is missing.",
            detail="SDC_MSRC_ROOT_KEY and SDC_MSRC_ROOT_CERT must exist.",
        )
    return settings.msrc_root_key, settings.msrc_root_cert


def _presentation_file(presentation_id: str) -> str:
    return f"{PRESENTED_PREFIX}-{presentation_id[:16]}.cbor"


def _submission_model(meta: dict[str, Any]) -> StoredSubmission:
    presentations = meta.get("presentations")
    return StoredSubmission(
        submission_id=str(meta.get("submission_id", "")),
        created_at=str(meta.get("created_at", "")),
        title=str(meta.get("title", "")),
        scitt_txid=meta.get("scitt_txid"),
        scitt_url=meta.get("scitt_url"),
        bundle_bytes=int(meta.get("bundle_bytes", 0)),
        presentations=(
            [str(item) for item in presentations]
            if isinstance(presentations, list)
            else []
        ),
    )


@router.get("/healthz", response_model=HealthResponse)
async def healthz(request: Request) -> HealthResponse:
    """Report liveness and whether demo issuance material is configured."""
    settings = get_services(request).settings
    configured = (
        settings.msrc_root_key is not None
        and settings.msrc_root_cert is not None
        and settings.msrc_root_key.is_file()
        and settings.msrc_root_cert.is_file()
    )
    return HealthResponse(service="mock-msrc", cli_configured=configured)


@router.get("/", response_class=Response)
async def index() -> Response:
    """Return a plain text notice describing the scope of this service."""
    return Response(content=DEMO_NOTICE + "\n", media_type="text/plain")


@router.post("/enroll", response_model=EnrollmentIssuance)
async def enroll(
    request: Request,
    subject: str = Form("Demo researcher"),
    public_key: UploadFile = File(...),
) -> EnrollmentIssuance:
    """Issue a short-lived leaf certificate for a submitted public key.

    Only a public key artifact is accepted. The service has no way to receive
    a private key: the upload is handed straight to the command line tool as
    the ``--public-key`` input.
    """
    services = get_services(request)
    settings = services.settings
    root_key, root_cert = _root_material(settings)
    subject_text = check_text_field("subject", subject, MAX_SHORT_CHARS, required=True)
    public_key_bytes = await read_upload(
        public_key, PUBLIC_KEY_UPLOAD, settings.max_pem_bytes
    )
    leaf = operations.issue_certificate(
        services.cli,
        root_key=root_key,
        root_cert=root_cert,
        public_key=public_key_bytes,
    )
    root_bytes = root_cert.read_bytes()

    enrollment_id = services.store.create_record(ENROLLMENTS)
    created_at = now_text()
    services.store.write_bytes(ENROLLMENTS, enrollment_id, LEAF_FILE, leaf)
    services.store.write_bytes(
        ENROLLMENTS, enrollment_id, PUBLIC_KEY_FILE, public_key_bytes
    )
    services.store.write_json(
        ENROLLMENTS,
        enrollment_id,
        META_FILE,
        {
            "enrollment_id": enrollment_id,
            "created_at": created_at,
            "subject": subject_text,
            "public_key_bytes": len(public_key_bytes),
        },
    )
    return EnrollmentIssuance(
        enrollment_id=enrollment_id,
        created_at=created_at,
        subject=subject_text,
        leaf_certificate_b64=base64.b64encode(leaf).decode("ascii"),
        root_certificate_b64=base64.b64encode(root_bytes).decode("ascii"),
    )


@router.get("/msrc-root")
async def msrc_root(request: Request) -> Response:
    """Return the demo certificate authority root for verifiers."""
    settings = get_services(request).settings
    _, root_cert = _root_material(settings)
    return Response(
        content=root_cert.read_bytes(),
        media_type="application/x-pem-file",
        headers={
            "content-disposition": 'attachment; filename="msrc-demo-root.pem"',
            "cache-control": "no-store",
        },
    )


@router.post("/submissions", response_model=StoredSubmission)
async def create_submission(
    request: Request,
    title: str = Form(""),
    scitt_txid: str = Form(""),
    scitt_url: str = Form(""),
    bundle: UploadFile = File(...),
) -> StoredSubmission:
    """Store an opaque proof bundle delivered by a researcher."""
    services = get_services(request)
    settings = services.settings
    payload = await read_upload(bundle, BUNDLE_UPLOAD, settings.max_bundle_bytes)
    submission_id = services.store.create_record(SUBMISSIONS)
    meta: dict[str, Any] = {
        "submission_id": submission_id,
        "created_at": now_text(),
        "title": check_text_field("title", title, MAX_SHORT_CHARS, required=False),
        "scitt_txid": check_text_field(
            "scitt_txid", scitt_txid, MAX_SHORT_CHARS, required=False
        )
        or None,
        "scitt_url": check_text_field(
            "scitt_url", scitt_url, MAX_SHORT_CHARS, required=False
        )
        or None,
        "bundle_bytes": len(payload),
        "presentations": [],
    }
    services.store.write_bytes(SUBMISSIONS, submission_id, BUNDLE_FILE, payload)
    services.store.write_json(SUBMISSIONS, submission_id, META_FILE, meta)
    return _submission_model(meta)


@router.get("/submissions", response_model=StoredSubmissionList)
async def list_submissions(request: Request) -> StoredSubmissionList:
    """List the stored submissions, newest first."""
    services = get_services(request)
    submissions: list[StoredSubmission] = []
    for record in services.store.list_records(SUBMISSIONS):
        if META_FILE not in record.artifacts:
            continue
        meta = services.store.read_json(SUBMISSIONS, record.record_id, META_FILE)
        submissions.append(_submission_model(meta))
    return StoredSubmissionList(submissions=submissions)


@router.get("/submissions/{submission_id}", response_model=StoredSubmission)
async def get_submission(request: Request, submission_id: str) -> StoredSubmission:
    """Return the metadata of one stored submission."""
    services = get_services(request)
    record = validate_record_id(submission_id)
    if not services.store.has_artifact(SUBMISSIONS, record, META_FILE):
        raise NotFoundError("No such submission.")
    return _submission_model(services.store.read_json(SUBMISSIONS, record, META_FILE))


@router.get("/submissions/{submission_id}/bundle")
async def download_submission(request: Request, submission_id: str) -> Response:
    """Download the opaque bundle bytes of a stored submission."""
    services = get_services(request)
    record = validate_record_id(submission_id)
    if not services.store.has_artifact(SUBMISSIONS, record, BUNDLE_FILE):
        raise NotFoundError("No such submission.")
    payload = services.store.read_bytes(SUBMISSIONS, record, BUNDLE_FILE)
    return artifact_response(
        payload,
        prefix="submission",
        record_id=record,
        suffix=".cbor",
        media_type="application/cbor",
    )


@router.post(
    "/submissions/{submission_id}/present", response_model=PresentationResponse
)
async def present_submission(
    request: Request, submission_id: str, selection: SelectionRequest
) -> PresentationResponse:
    """Produce a redacted bundle from a stored submission."""
    services = get_services(request)
    record = validate_record_id(submission_id)
    if not services.store.has_artifact(SUBMISSIONS, record, BUNDLE_FILE):
        raise NotFoundError("No such submission.")
    payload = services.store.read_bytes(SUBMISSIONS, record, BUNDLE_FILE)
    presented = operations.present_bundle(services.cli, payload, selection)

    presentation_id = new_record_id()
    file_name = _presentation_file(presentation_id)
    services.store.write_bytes(SUBMISSIONS, record, file_name, presented)
    meta = services.store.read_json(SUBMISSIONS, record, META_FILE)
    presentations = meta.get("presentations")
    meta["presentations"] = (
        [str(item) for item in presentations] if isinstance(presentations, list) else []
    ) + [presentation_id]
    services.store.write_json(SUBMISSIONS, record, META_FILE, meta)
    return PresentationResponse(
        presentation_id=presentation_id,
        bundle_id=record,
        bundle_bytes=len(presented),
        download_url=(f"/submissions/{record}/presentations/{presentation_id}/bundle"),
        redacted_fields=list(selection.redact_fields),
        redacted_body_chunks=list(selection.redact_body_chunks),
    )


@router.get("/submissions/{submission_id}/presentations/{presentation_id}/bundle")
async def download_presentation(
    request: Request, submission_id: str, presentation_id: str
) -> Response:
    """Download a redacted bundle produced from a stored submission."""
    services = get_services(request)
    record = validate_record_id(submission_id)
    presentation = validate_record_id(presentation_id)
    file_name = _presentation_file(presentation)
    if not services.store.has_artifact(SUBMISSIONS, record, file_name):
        raise NotFoundError("No such presentation.")
    payload = services.store.read_bytes(SUBMISSIONS, record, file_name)
    return artifact_response(
        payload,
        prefix="presented-bundle",
        record_id=presentation,
        suffix=".cbor",
        media_type="application/cbor",
    )


def create_app(services: Services | None = None) -> FastAPI:
    """Build the mock MSRC application."""
    app = FastAPI(
        title="Mock MSRC service (demonstration only)",
        description=DEMO_NOTICE,
        version="0.1.0",
        docs_url="/api/docs",
        openapi_url="/api/openapi.json",
    )
    attach_services(app, services if services is not None else build_services())
    install_error_handlers(app)
    app.include_router(router)
    return app
